apiVersion: v1
kind: Pod
metadata:
  name: lk-app-frontend
  labels:
    name: frontend
spec:
  containers:
  - name: lk-app-frontend
    image: localhost:5000/lk-app-frontend:latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
