apiVersion: v1
kind: Pod
metadata:
  name: lk-app-backend
  labels:
    name: backend
spec:
  containers:
  - name: lk-app-backend
    image: localhost:5000/lk-app-backend:latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
