apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lk-app-backend
  labels:
    name: backend
spec:
  replicas: 6
  selector:
    matchLabels:
      name: backend
  template:
    metadata:
      labels:
        name: backend
    spec:
      containers:
        - name: lk-app-backend
          image: localhost:5000/lk-app-backend:latest
